services:
    frontend-user1:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - '3001:3000'
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules
            - ./package.json:/usr/src/app/package.json
        networks:
            - vemo-network

    frontend-user2:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - '3002:3000'
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules
            - ./package.json:/usr/src/app/package.json
        networks:
            - vemo-network

    backend-user1:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '5051:5050'
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/usr/src/app/backend
            - /usr/src/app/backend/node_modules
            - ./package.json:/usr/src/app/package.json
        networks:
            - vemo-network

    backend-user2:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '5052:5050'
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/usr/src/app/backend
            - /usr/src/app/backend/node_modules
            - ./package.json:/usr/src/app/package.json
        networks:
            - vemo-network

    backend-user3:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '5053:5050'
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/usr/src/app/backend
            - /usr/src/app/backend/node_modules
            - ./package.json:/usr/src/app/package.json
        networks:
            - vemo-network

networks:
    vemo-network:
        driver: bridge
