version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - ./package.json:/usr/src/app/package.json
    networks:
      - vemo-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5050:5050'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
      - ./package.json:/usr/src/app/package.json
    networks:
      - vemo-network

networks:
  vemo-network:
    driver: bridge
